import AppKit
import Combine
import Foundation

struct OMacOSClipboardEntry: Codable, Identifiable, Equatable {
    let id: UUID
    let text: String
    let capturedAt: Date
}

@MainActor
final class OMacOSClipboardStore: NSObject, ObservableObject {
    @Published private(set) var entries: [OMacOSClipboardEntry] = []

    private let pasteboard: NSPasteboard
    private let historyURL: URL
    private var lastChangeCount: Int
    private var pollingTimer: Timer?

    init(
        pasteboard: NSPasteboard = .general,
        environment: [String: String] = ProcessInfo.processInfo.environment
    ) {
        self.pasteboard = pasteboard
        let homeDirectory = environment["OMACOS_TEST_HOME"] ?? NSHomeDirectory()
        historyURL = URL(fileURLWithPath: homeDirectory)
            .appendingPathComponent(".local/state/omacos/clipboard-history.json")
        lastChangeCount = pasteboard.changeCount
        super.init()
        loadHistory()
    }

    /// Starts local clipboard capture. Concealed and auto-generated pasteboard contents are never retained.
    func startCapture() {
        pollingTimer = Timer.scheduledTimer(
            timeInterval: 0.8,
            target: self,
            selector: #selector(capturePasteboardChange),
            userInfo: nil,
            repeats: true
        )
    }

    func copy(_ entry: OMacOSClipboardEntry) {
        pasteboard.clearContents()
        pasteboard.setString(entry.text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        promote(entry)
    }

    func paste(_ entry: OMacOSClipboardEntry) {
        copy(entry)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.15) {
            _ = OMacOSCommandRunner.run(
                executable: "/usr/bin/osascript",
                arguments: ["-e", "tell application \"System Events\" to keystroke \"v\" using command down"]
            )
        }
    }

    func remove(_ entry: OMacOSClipboardEntry) {
        entries.removeAll { $0.id == entry.id }
        persistHistory()
    }

    func clear() {
        entries = []
        persistHistory()
    }

    @objc private func capturePasteboardChange() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set(pasteboard.types ?? [])
        let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        guard !types.contains(concealedType), !types.contains(autoGeneratedType),
              let text = pasteboard.string(forType: .string) else {
            return
        }

        let normalizedText = Self.normalizedClipboardText(text)
        guard !normalizedText.isEmpty else { return }
        promote(OMacOSClipboardEntry(id: UUID(), text: normalizedText, capturedAt: Date()))
    }

    private func promote(_ entry: OMacOSClipboardEntry) {
        entries.removeAll { $0.text == entry.text }
        entries.insert(entry, at: 0)
        if entries.count > 100 {
            entries.removeLast(entries.count - 100)
        }
        persistHistory()
    }

    private func loadHistory() {
        guard let data = try? Data(contentsOf: historyURL),
              let decodedEntries = try? JSONDecoder().decode([OMacOSClipboardEntry].self, from: data) else {
            return
        }
        entries = Array(decodedEntries.prefix(100))
    }

    private func persistHistory() {
        do {
            try FileManager.default.createDirectory(
                at: historyURL.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            let data = try JSONEncoder().encode(entries)
            try data.write(to: historyURL, options: .atomic)
        } catch {
            // Clipboard capture must not crash the desktop shell when persistence is unavailable.
        }
    }

    nonisolated static func normalizedClipboardText(_ text: String) -> String {
        text.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
